#!/bin/bash

###
#       @author: msune
#	@organization: i2CAT
#	@project: Ofelia FP7
#	@description: pre-install module 
###

#inform user
printHeader "info#" "Using default pre-install-hook module..."

#shutdown apache
print "Nothing to do..."

#Check if installations is for OFELIA or not
askForOfeliaInstallation

