#!/bin/bash

###
#       @author: msune
#	@organization: i2CAT
#	@project: Ofelia FP7
#	@description: post-upgrade-hook module 
###

#inform user
printHeader "info#" "Using default post-upgrade-hook module..."

#Starting OXA 
print "Starting oxad..." 
/usr/sbin/service oxad restart


