#!/bin/bash

###
#       @author: msune
#	@organization: i2CAT
#	@project: Ofelia FP7
#	@description: pre-upgrade-module 
###

#inform user
printHeader "info#" "Using default pre-upgrade-hook module..."

#shutdown apache
print "Nothing to do..."


