#!/bin/bash

###
#       @author: msune
#	@organization: i2CAT
#	@project: Ofelia FP7
#	@description: Version checkings 
###

#inform user
printHeader "info#" "Using default upgrade module..."

print "Checking for new versions of the VM template..."
source "$CURRENT_DIRECTORY/lib/template"
