Document: foam
Title: Debian foam Manual
Author: <insert document author here>
Abstract: This manual describes what foam is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/foam/foam.sgml.gz

Format: postscript
Files: /usr/share/doc/foam/foam.ps.gz

Format: text
Files: /usr/share/doc/foam/foam.text.gz

Format: HTML
Index: /usr/share/doc/foam/html/index.html
Files: /usr/share/doc/foam/html/*.html
