#!/bin/bash

###
#   @author: lbergesio 
#   @organization: i2CAT
#   @project: Ofelia FP7
#   @description: backup module
###

#Import email util
source sendEmailUtil

#Email presets
EMAIL_SUBJECT="[OFELIA CF] Server Monitor Report"
EMAIL_MESSAGE="The Server Monitoring Utilty could not backup some of the databases. Here is the report: \n\n"

#IPs
VM_IP=10.216.140.11
VM_PORT=7373
VM_USER=root

SERVER_IP=10.216.140.3
SERVER_PORT=7373
SERVER_USER=root

#DIRS
MON_DIR=/opt/ofelia/monitoring/
BACKUP_DIR=/home/leo/dataBaseBackupFiles/
SETTINGS_PATHS="expedient.clearinghouse.settings vt_manager.settings.settingsLoader openflow.optin_manager.settings"

cd $MON_DIR
for SETTINGS in $SETTINGS_PATHS
do
        FILE=`echo $SETTINGS | awk -F. '{print $1}'`
        if [ "$FILE" == "openflow" ]; then
                FILE=optin_manager
        fi
        PYTHON_PATH=/opt/ofelia/$FILE/src/python
        REPORT=`python sqlDump.py $BACKUP_DIR/$FILE $SETTINGS $PYTHON_PATH 2>&1`
        if [[ $? != 0 ]]; then
		echo "\nCould not dump data from $FILE database!\n$REPORT\n"
                sendEmail "$EMAIL_SUBJECT" "$EMAIL_MESSAGE $REPORT"
	fi
done

scp -P$SERVER_PORT $BACKUP_DIR/* $SERVER_USER@$SERVER_IP:/home/leo/dataBaseBackupFiles/.
if [[ $? != 0 ]]; then
	echo "Could not scp remote server"
	sendEmail "$EMAIL_SUBJECT" "Could not scp remote server"
fi
rm $BACKUP_DIR/* || echo "Temp files at $BACKUP_DIR could not be deleted"
