#!/bin/bash

###
#   @author: lbergesio
#   @organization: i2CAT
#   @project: Ofelia FP7
#   @description: install module 
###

#Import email util
source sendEmailUtil

#SERVER URL
SERVER="https://10.216.140.11"

#Email presets
EMAIL_SUBJECT="[OFELIA CF] Server Monitor Report"
EMAIL_MESSAGE="The Server Monitoring Utilty has detected an error. Here is the report: \n\n"


LOG="`wget $SERVER --no-check-certificate --server-response --spider 2>&1`"

NO_ERROR=`echo $LOG | grep "Remote file exists" | sed 's/--//g'`
ERROR_500=`echo $LOG | grep "500 Internal Server Error" | sed 's/--//g'`
ERROR_CNX_REFUSED=`echo $LOG | grep "Connection refused" | sed 's/--//g'`
ERROR_NO_ROUTE=`echo $LOG | grep "No route to host" | sed 's/--//g'`


if [[ ! -z "$ERROR_500" || ! -z "$ERROR_CNX_REFUSED" || ! -z "$ERROR_NO_ROUTE" ]]; then
	sendEmail "$EMAIL_SUBJECT" "$EMAIL_MESSAGE $ERROR_500 $ERROR_CNX_REFUSED $ERROR_NO_ROUTE"
fi

