#!/bin/bash

###
#   @author: lbergesio 
#   @organization: i2CAT
#   @project: Ofelia FP7
#   @description: backup module
###

python sqlDump.py "home/leo/dataBaseBackupFiles/temp" "expedient.clearinghouse.settings" "/opt/ofelia/expedient/src/pyton" 2>&1
echo "EXIT STATUS: $?"
