from django.db import models

class Profile(models.Model):
    sid = models.CharField(max_length=50, primary_key=True)
    password = models.CharField(max_length=50)
    name = models.CharField(max_length=200)
    email = models.EmailField(max_length=100)
    phone = models.CharField(max_length=15, null=True)

class Admin(models.Model):
    sid = models.ForeignKey(Profile)
    max_priority_level = models.IntegerField()
    auth_module = models.CharField(max_length=200, null=True)
    supervisor_sid = models.CharField(max_length=50, null=True)

    mac_src_s = models.IntegerField(null=True)
    mac_src_e = models.IntegerField(null=True)
    mac_dst_s = models.IntegerField(null=True)
    mac_dst_e = models.IntegerField(null=True)
    eth_type_s = models.IntegerField(null=True)
    eth_type_e = models.IntegerField(null=True)
    vlan_id_s = models.IntegerField(null=True)
    vlan_id_e = models.IntegerField(null=True)
    vlan_priority_s = models.IntegerField(null=True)
    vlan_priority_e = models.IntegerField(null=True)
    ip_src_s = models.IntegerField(null=True)
    ip_src_e = models.IntegerField(null=True)
    ip_dst_s = models.IntegerField(null=True)
    ip_dst_e = models.IntegerField(null=True)
    ip_proto_s = models.IntegerField(null=True)
    ip_proto_e = models.IntegerField(null=True)
    ip_tos_s = models.IntegerField(null=True)
    ip_tos_e = models.IntegerField(null=True)
    tp_src_s = models.IntegerField(null=True)
    tp_src_e = models.IntegerField(null=True)
    tp_dst_s = models.IntegerField(null=True)
    tp_dst_e = models.IntegerField(null=True)

class User(models.Model):
    sid = models.ForeignKey(Profile)
    priority_level = models.IntegerField()
    supervisor = models.ForeignKey(Admin)

    mac_src_s = models.IntegerField(null=True)
    mac_src_e = models.IntegerField(null=True)
    mac_dst_s = models.IntegerField(null=True)
    mac_dst_e = models.IntegerField(null=True)
    eth_type_s = models.IntegerField(null=True)
    eth_type_e = models.IntegerField(null=True)
    vlan_id_s = models.IntegerField(null=True)
    vlan_id_e = models.IntegerField(null=True)
    vlan_priority_s = models.IntegerField(null=True)
    vlan_priority_e = models.IntegerField(null=True)
    ip_src_s = models.IntegerField(null=True)
    ip_src_e = models.IntegerField(null=True)
    ip_dst_s = models.IntegerField(null=True)
    ip_dst_e = models.IntegerField(null=True)
    ip_proto_s = models.IntegerField(null=True)
    ip_proto_e = models.IntegerField(null=True)
    ip_tos_s = models.IntegerField(null=True)
    ip_tos_e = models.IntegerField(null=True)
    tp_src_s = models.IntegerField(null=True)
    tp_src_e = models.IntegerField(null=True)
    tp_dst_s = models.IntegerField(null=True)
    tp_dst_e = models.IntegerField(null=True)

class Request(models.Model):
    sid = models.ForeignKey(Profile)
    priority_level = models.IntegerField()
    supervisor = models.ForeignKey(Admin)
    request_type = models.IntegerField() #0 user / 1 Admin

    mac_src_s = models.IntegerField(null=True)
    mac_src_e = models.IntegerField(null=True)
    mac_dst_s = models.IntegerField(null=True)
    mac_dst_e = models.IntegerField(null=True)
    eth_type_s = models.IntegerField(null=True)
    eth_type_e = models.IntegerField(null=True)
    vlan_id_s = models.IntegerField(null=True)
    vlan_id_e = models.IntegerField(null=True)
    vlan_priority_s = models.IntegerField(null=True)
    vlan_priority_e = models.IntegerField(null=True)
    ip_src_s = models.IntegerField(null=True)
    ip_src_e = models.IntegerField(null=True)
    ip_dst_s = models.IntegerField(null=True)
    ip_dst_e = models.IntegerField(null=True)
    ip_proto_s = models.IntegerField(null=True)
    ip_proto_e = models.IntegerField(null=True)
    ip_tos_s = models.IntegerField(null=True)
    ip_tos_e = models.IntegerField(null=True)
    tp_src_s = models.IntegerField(null=True)
    tp_src_e = models.IntegerField(null=True)
    tp_dst_s = models.IntegerField(null=True)
    tp_dst_e = models.IntegerField(null=True)