SFA_DATA_DIR = "/opt/ofelia/optin_manager/src/python/openflow/optin_manager/sfa/my_roots/"
SFA_INTERFACE_HRN ="ocf_of"
MY_ROOTS_DIR = "/opt/ofelia/optin_manager/src/python/openflow/optin_manager/sfa/my_roots/"
TRUSTED_ROOTS_DIR = "/opt/ofelia/optin_manager/src/python/openflow/optin_manager/sfa/trusted_roots/"
SFA_CREDENTIAL_SCHEMA = "/opt/ofelia/optin_manager/src/python/openflow/optin_manager/sfa/schemas/credential.xsd"
