"""empty message

Revision ID: 1998d2a1b89a
Revises: None
Create Date: 2014-05-16 11:23:54.888968

"""

# revision identifiers, used by Alembic.
revision = '1998d2a1b89a'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table(u'vt_manager_virtualmachine_allocated')
    op.drop_table(u'vt_manager_vtserver_allocated_vms')
    op.drop_table(u'vt_manager_virtualmachine_allocated_expiration')
    op.add_column('vt_manager_expiration', sa.Column('end_time', sa.DateTime(), nullable=False))
    op.add_column('vt_manager_expiration', sa.Column('start_time', sa.DateTime(), nullable=False))
    op.drop_column('vt_manager_expiration', u'expiration')
    op.drop_index(u'vt_manager_ip4range_ips_80d540d2', table_name='vt_manager_ip4range_ips')
    op.drop_index(u'vt_manager_ip4range_ips_84ff4fa8', table_name='vt_manager_ip4range_ips')
    op.drop_index(u'vt_manager_ip4slot_81c6309d', table_name='vt_manager_ip4slot')
    op.drop_index(u'vt_manager_macrange_macs_c7fc53c2', table_name='vt_manager_macrange_macs')
    op.drop_index(u'vt_manager_macrange_macs_cecab7cc', table_name='vt_manager_macrange_macs')
    op.drop_index(u'vt_manager_macslot_e202da94', table_name='vt_manager_macslot')
    op.drop_index(u'vt_manager_networkinterface_883da452', table_name='vt_manager_networkinterface')
    op.drop_index(u'vt_manager_networkinterface_connectedTo_3d6a8685', table_name='vt_manager_networkinterface_connectedTo')
    op.drop_index(u'vt_manager_networkinterface_connectedTo_efd0ffce', table_name='vt_manager_networkinterface_connectedTo')
    op.drop_index(u'vt_manager_networkinterface_ip4s_1bce8ac1', table_name='vt_manager_networkinterface_ip4s')
    op.drop_index(u'vt_manager_networkinterface_ip4s_80d540d2', table_name='vt_manager_networkinterface_ip4s')
    op.add_column('vt_manager_virtualmachine', sa.Column('memory_mb', sa.Integer(), nullable=True))
    op.add_column('vt_manager_virtualmachine', sa.Column('type', sa.String(length=1024), server_default='xen', nullable=False))
    op.add_column('vt_manager_virtualmachine', sa.Column('urn', sa.String(length=1024), nullable=True))
    op.drop_column('vt_manager_virtualmachine', u'memory')
    op.drop_index(u'vt_manager_virtualmachine_networkInterfaces_1bce8ac1', table_name='vt_manager_virtualmachine_networkInterfaces')
    op.drop_index(u'vt_manager_virtualmachine_networkInterfaces_b0957e26', table_name='vt_manager_virtualmachine_networkInterfaces')
    op.drop_index(u'vt_manager_vtserver_networkInterfaces_1bce8ac1', table_name='vt_manager_vtserver_networkInterfaces')
    op.drop_index(u'vt_manager_vtserver_networkInterfaces_f6f1739f', table_name='vt_manager_vtserver_networkInterfaces')
    op.drop_index(u'vt_manager_vtserver_subscribedIp4Ranges_84ff4fa8', table_name='vt_manager_vtserver_subscribedIp4Ranges')
    op.drop_index(u'vt_manager_vtserver_subscribedIp4Ranges_f6f1739f', table_name='vt_manager_vtserver_subscribedIp4Ranges')
    op.drop_index(u'vt_manager_vtserver_subscribedMacRanges_cecab7cc', table_name='vt_manager_vtserver_subscribedMacRanges')
    op.drop_index(u'vt_manager_vtserver_subscribedMacRanges_f6f1739f', table_name='vt_manager_vtserver_subscribedMacRanges')
    op.drop_index(u'vt_manager_xenserver_vms_ae321129', table_name='vt_manager_xenserver_vms')
    op.drop_index(u'vt_manager_xenserver_vms_e0a79327', table_name='vt_manager_xenserver_vms')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(u'vt_manager_xenserver_vms_e0a79327', 'vt_manager_xenserver_vms', [u'xenvm_id'], unique=False)
    op.create_index(u'vt_manager_xenserver_vms_ae321129', 'vt_manager_xenserver_vms', [u'xenserver_id'], unique=False)
    op.create_index(u'vt_manager_vtserver_subscribedMacRanges_f6f1739f', 'vt_manager_vtserver_subscribedMacRanges', [u'vtserver_id'], unique=False)
    op.create_index(u'vt_manager_vtserver_subscribedMacRanges_cecab7cc', 'vt_manager_vtserver_subscribedMacRanges', [u'macrange_id'], unique=False)
    op.create_index(u'vt_manager_vtserver_subscribedIp4Ranges_f6f1739f', 'vt_manager_vtserver_subscribedIp4Ranges', [u'vtserver_id'], unique=False)
    op.create_index(u'vt_manager_vtserver_subscribedIp4Ranges_84ff4fa8', 'vt_manager_vtserver_subscribedIp4Ranges', [u'ip4range_id'], unique=False)
    op.create_index(u'vt_manager_vtserver_networkInterfaces_f6f1739f', 'vt_manager_vtserver_networkInterfaces', [u'vtserver_id'], unique=False)
    op.create_index(u'vt_manager_vtserver_networkInterfaces_1bce8ac1', 'vt_manager_vtserver_networkInterfaces', [u'networkinterface_id'], unique=False)
    op.create_index(u'vt_manager_virtualmachine_networkInterfaces_b0957e26', 'vt_manager_virtualmachine_networkInterfaces', [u'virtualmachine_id'], unique=False)
    op.create_index(u'vt_manager_virtualmachine_networkInterfaces_1bce8ac1', 'vt_manager_virtualmachine_networkInterfaces', [u'networkinterface_id'], unique=False)
    op.add_column('vt_manager_virtualmachine', sa.Column(u'memory', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('vt_manager_virtualmachine', 'urn')
    op.drop_column('vt_manager_virtualmachine', 'type')
    op.drop_column('vt_manager_virtualmachine', 'memory_mb')
    op.create_index(u'vt_manager_networkinterface_ip4s_80d540d2', 'vt_manager_networkinterface_ip4s', [u'ip4slot_id'], unique=False)
    op.create_index(u'vt_manager_networkinterface_ip4s_1bce8ac1', 'vt_manager_networkinterface_ip4s', [u'networkinterface_id'], unique=False)
    op.create_index(u'vt_manager_networkinterface_connectedTo_efd0ffce', 'vt_manager_networkinterface_connectedTo', [u'to_networkinterface_id'], unique=False)
    op.create_index(u'vt_manager_networkinterface_connectedTo_3d6a8685', 'vt_manager_networkinterface_connectedTo', [u'from_networkinterface_id'], unique=False)
    op.create_index(u'vt_manager_networkinterface_883da452', 'vt_manager_networkinterface', [u'mac_id'], unique=False)
    op.create_index(u'vt_manager_macslot_e202da94', 'vt_manager_macslot', [u'macRange_id'], unique=False)
    op.create_index(u'vt_manager_macrange_macs_cecab7cc', 'vt_manager_macrange_macs', [u'macrange_id'], unique=False)
    op.create_index(u'vt_manager_macrange_macs_c7fc53c2', 'vt_manager_macrange_macs', [u'macslot_id'], unique=False)
    op.create_index(u'vt_manager_ip4slot_81c6309d', 'vt_manager_ip4slot', [u'ipRange_id'], unique=False)
    op.create_index(u'vt_manager_ip4range_ips_84ff4fa8', 'vt_manager_ip4range_ips', [u'ip4range_id'], unique=False)
    op.create_index(u'vt_manager_ip4range_ips_80d540d2', 'vt_manager_ip4range_ips', [u'ip4slot_id'], unique=False)
    op.add_column('vt_manager_expiration', sa.Column(u'expiration', sa.DATETIME(), nullable=False))
    op.drop_column('vt_manager_expiration', 'start_time')
    op.drop_column('vt_manager_expiration', 'end_time')
    op.create_table(u'vt_manager_virtualmachine_allocated_expiration',
    sa.Column(u'id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column(u'vm_uuid', mysql.VARCHAR(length=1024), nullable=False),
    sa.Column(u'expiration_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint(u'id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'MyISAM'
    )
    op.create_table(u'vt_manager_vtserver_allocated_vms',
    sa.Column(u'id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column(u'vtserver_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column(u'allocated_vm_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint(u'id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'MyISAM'
    )
    op.create_table(u'vt_manager_virtualmachine_allocated',
    sa.Column(u'id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column(u'name', mysql.VARCHAR(length=512), nullable=False),
    sa.Column(u'uuid', mysql.VARCHAR(length=1024), nullable=False),
    sa.Column(u'memory_mb', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column(u'number_of_cpus', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column(u'hd_size_mb', mysql.DOUBLE(), nullable=True),
    sa.Column(u'project_uuid', mysql.VARCHAR(length=1024), nullable=False),
    sa.Column(u'project_name', mysql.VARCHAR(length=1024), nullable=False),
    sa.Column(u'slice_uuid', mysql.VARCHAR(length=1024), nullable=False),
    sa.Column(u'slice_name', mysql.VARCHAR(length=512), nullable=False),
    sa.Column(u'server_uuid', mysql.VARCHAR(length=1024), nullable=False),
    sa.Column(u'virtualization_technology', mysql.VARCHAR(length=512), nullable=False),
    sa.PrimaryKeyConstraint(u'id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'MyISAM'
    )
    ### end Alembic commands ###
