#!/bin/bash


function downloadTemplate
{
        echo "" 
        echo "OK of everything is correct, this  may take a while (approx. 1.2GB)..."
        if [ $OFELIA == 1 ];then
        /usr/bin/wget --progress=bar:force --no-check-certificate --user=$USERNAME --password=$PASSWORD --output-document $OXA_DIRECTORY/cache/templates/default/default.tar.gz  https://alpha.fp7-ofelia.eu/storage/images/xen/templates/Debian/0.1/default.tar.gz || ( rm $OXA_DIRECTORY/cache/templates/default/default.tar.gz && error "Cannot download template from storage system!!!" )
        else
        /usr/bin/wget --progress=bar:force --no-check-certificate --output-document $OXA_DIRECTORY/cache/templates/default/default.tar.gz  http://codebasin.net/redmine/attachments/download/23/default.tar.gz || ( rm $OXA_DIRECTORY/cache/templates/default/default.tar.gz && error "Cannot download template from storage system!!!" )
        fi
}

function downloadTemplateHash
{
        echo ""
        echo "Attempting to download HASH file of the template..."     
        if [ $OFELIA == 1 ];then
                /usr/bin/wget --progress=bar:force --no-check-certificate --user=$USERNAME --password=$PASSWORD --output-document $OXA_DIRECTORY/cache/templates/default/.default.hash  https://alpha.fp7-ofelia.eu/storage/images/xen/templates/Debian/0.1/default.hash || ( rm $OXA_DIRECTORY/cache/templates/default/.default.hash && error "Cannot download HASH for the template from storage system!!!" $NO_RESCUE )
        else
                 /usr/bin/wget --progress=bar:force --no-check-certificate --output-document $OXA_DIRECTORY/cache/templates/default/.default.hash  http://codebasin.net/redmine/attachments/download/26/default.tar.gz.hash || ( rm $OXA_DIRECTORY/cache/templates/default/.default.hash && error "Cannot download HASH for the template from storage system!!!" $NO_RESCUE )
        fi
}

print "VM template installation..."

        if [ $OFELIA == 1 ];then
                echo "Please enter the USERNAME for the OFELIA storage system to download the default template. Credentials are the same ones used in Ofelia's TRAC, WIKI and SVN (email). Usernames and passwords will NOT be stored."

                echo -n "Username:"
                read USERNAME
                echo -n "Password:"

                /bin/stty -echo
                read PASSWORD
                /bin/stty echo
        fi
        #Mkdir
        mkdir -p $OXA_DIRECTORY/cache/templates/default

        #Attempting to download HASH file of the template..     
        downloadTemplateHash

        local HASH=`cat $OXA_DIRECTORY/cache/templates/default/default.hash > /dev/null 2>&1 `
        local NEWHASH=`cat $OXA_DIRECTORY/cache/templates/default/.default.hash > /dev/null 2>&1`

        if [ ! -f $OXA_DIRECTORY/cache/templates/default/default.tar.gz -o "$NEWHASH"  != "$HASH" ];then
                downloadTemplate
                mv -f $OXA_DIRECTORY/cache/templates/default/.default.hash $OXA_DIRECTORY/cache/templates/default/default.hash
        else
                if [ "$FORCE" == 0 ]; then
                        print ""
                        warning "Default template file already exists and is up-to-date; skipping..."
                        print ""
                else
                        confirm "Default template file already exists. Do you want to OVERWRITE it (It will not be backuped!)." $DONT_ABORT $NO_RESCUE

                        if [ $? == 0 ]; then
                                downloadTemplate
                                mv -f $OXA_DIRECTORY/cache/templates/default/.default.hash $OXA_DIRECTORY/cache/templates/default/default.hash
                        fi

                fi

        fi
