#!/bin/bash

#Constants
EDITORS="vi vim emacs nano pico"

#Copy from template
printHeader ">" "Copying settings file from template..."

if [ -f $SRC_DIR/bin/mySettings.py ];then
	warning "mySettings.py file already exists."

	if [ "$FORCE" == "1" ]; then
		confirm "Overwrite currently installed mySettings.py." $DONT_ABORT
		if [ $? == 0 ]; then			
			cp $SRC_DIR/bin/mySettings-example.py $SRC_DIR/bin/mySettings.py -f || error "Cannot copy mySettings.py"
		fi 
	else
		print "Skipping copy (will not be overwritten)"
	fi
else
	print "$SRC_DIR/bin/mySettings-example.py -> $SRC_DIR/bin/mySettings.py "
	cp $SRC_DIR/bin/mySettings-example.py $SRC_DIR/bin/mySettings.py -f || error "Cannot copy mySettings.py"
fi

#Choose editor
printHeader ">" "Choosing the editor..."
select editor in $EDITORS;
do
	if [ -z $editor ]; then
		print "Invalid option $editor"
		continue
	fi
	print ""
	EDITOR=$editor
	print "Your are going to use $EDITOR for file manipulation..."
	break;
done

#Edit file
printHeader ">" "Editing settings..."
while :	
do
	print "Now you are going to edit the file $SRC_DIR/bin/mySettings.py using $EDITOR. Save the modifications and do NOT exit using Ctrl+C..."
	warning "Make sure you uncomment and define a STRONG password for the XMLRPC interface"
	pause ""
	eval $EDITOR $SRC_DIR/bin/mySettings.py
	print ""
	pause "Now the contents of the file will be shown for a final review. You can scroll up/down to verify the settings. Press 'q' to continue..."
	less $SRC_DIR/bin/mySettings.py
	
	confirm "Is it correct OK." $DONT_ABORT $NO_RESCUE

	if [ $? == 0 ]; then
		break
	fi	

done

